import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/calm.module.css";
import { Typography, Grid } from "@mui/material"

import { useState, useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [bpm, setBpm] = useState(110)

  useEffect(() => {
    setTimeout(() => {
      if (bpm >= 90) setBpm(bpm => bpm - Math.floor(Math.random() * 5))
    }, 2000)
  }, [bpm])

  return (
    <>
      <Head>
        <title>AI Meditation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grid container spacing={2}>
          <Grid item xs={6} sx={{display: 'flex', flexDirection: 'column', alignItems: 'center'}} onClick={() => window.location.replace('/calm')}>
              <img className={styles.coverimage} src="/logo.png" alt="calm" width={150} height={150} style={{marginBottom: '20px'}}/>
                <Typography variant="h6" className={styles.songtitle}>
                    Calm
                </Typography>
          </Grid>
          <Grid item xs={6} sx={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
              <img className={styles.coverimage} src="/meditate.png" alt="calm" width={150} height={150} style={{marginBottom: '20px'}}/>
              <Typography variant="h6" className={styles.songtitle}>
                  Meditate
              </Typography>
          </Grid>
          <Grid item xs={6} sx={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
              <img className={styles.coverimage} src="/nature.png" alt="calm" width={150} height={150} style={{marginBottom: '20px'}}/>
              <Typography variant="h6" className={styles.songtitle}>
                  Nature
              </Typography>
          </Grid>
          <Grid item xs={6} sx={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
              <img className={styles.coverimage} src="/graph.png" alt="calm" width={150} height={150} style={{marginBottom: '20px'}}/>
              <Typography variant="h6" className={styles.songtitle}>
                  Tracker
              </Typography>
          </Grid>
        </Grid>
        <Typography variant="h4" sx={{marginTop: '200px'}}>Total Sessions: 5</Typography>
        <Typography variant="h6" sx={{marginTop: '10px'}}>see stats</Typography>
      </main>
    </>
  );
}